from .config import get_settings


DEFAULT_NSE_UNIVERSE = [
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "BHARTIARTL", "SBIN",
    "LT", "ITC", "HINDUNILVR", "BAJFINANCE", "KOTAKBANK", "AXISBANK", "M&M",
    "SUNPHARMA", "MARUTI", "HCLTECH", "NTPC", "TITAN", "ULTRACEMCO", "ONGC",
    "TATAMOTORS", "POWERGRID", "ADANIENT", "ADANIPORTS", "WIPRO", "COALINDIA",
    "ASIANPAINT", "BAJAJFINSV", "NESTLEIND", "JSWSTEEL", "TATASTEEL", "GRASIM",
    "HINDALCO", "TECHM", "CIPLA", "DRREDDY", "BRITANNIA", "EICHERMOT",
    "DIVISLAB", "APOLLOHOSP", "HEROMOTOCO", "BPCL", "BAJAJ-AUTO", "TATACONSUM",
    "SHRIRAMFIN", "INDUSINDBK", "UPL", "SBILIFE", "HDFCLIFE", "ADANIGREEN",
    "ADANIPOWER", "AMBUJACEM", "DMART", "BANKBARODA", "BEL", "BOSCHLTD",
    "CANBK", "CHOLAFIN", "DABUR", "DLF", "GAIL", "GODREJCP", "HAL", "HAVELLS",
    "ICICIGI", "ICICIPRULI", "INDIGO", "IOC", "IRCTC", "JINDALSTEL", "JSWENERGY",
    "LICI", "LODHA", "LTIM", "MOTHERSON", "NAUKRI", "PIDILITIND", "PNB",
    "RECLTD", "SHREECEM", "SIEMENS", "TATAPOWER", "TORNTPHARM", "TRENT",
    "TVSMOTOR", "VEDL", "VBL", "ZYDUSLIFE", "ABB", "ALKEM", "AUROPHARMA",
    "BANDHANBNK", "BERGEPAINT", "BIOCON", "COLPAL", "CONCOR", "FEDERALBNK",
    "HINDPETRO", "IDEA", "INDHOTEL", "LUPIN", "MARICO", "MUTHOOTFIN", "NMDC",
    "OBEROIRLTY", "PAGEIND", "PERSISTENT", "PETRONET", "SAIL", "SRF", "YESBANK",
]


def get_universe() -> list[str]:
    custom = get_settings().custom_universe.strip()
    if custom:
        return [item.strip().upper().replace(".NS", "") for item in custom.split(",") if item.strip()]
    return DEFAULT_NSE_UNIVERSE
